In [1]:
import pandas as pd
import os
os.getcwd()

'/Users/deepakm/mywork/Python_S1/cricket_data'

In [7]:
dlv=pd.read_csv("deliveries.csv")
dlv.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [22]:
dlv.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [23]:
dlm=pd.merge(dlv[['match_id', 'inning', 'batting_team']],mtch[mtchcols],how='left',left_on='match_id',right_on='id')
dlm.head()

,match_id,inning,batting_team,id,season,winner,toss_decision
0,1,1,Sunrisers Hyderabad,1,2017,Sunrisers Hyderabad,field
1,1,1,Sunrisers Hyderabad,1,2017,Sunrisers Hyderabad,field
2,1,1,Sunrisers Hyderabad,1,2017,Sunrisers Hyderabad,field
3,1,1,Sunrisers Hyderabad,1,2017,Sunrisers Hyderabad,field
4,1,1,Sunrisers Hyderabad,1,2017,Sunrisers Hyderabad,field

In [18]:
dlm=pd.merge(dlm,nmt,left_on='winner',right_on='FullName',how='left')
dlm.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,player_dismissed,dismissal_kind,fielder,id,season,winner_x,toss_decision,FullName,ShortName,winner_y
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH,Sunrisers Hyderabad
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH,Sunrisers Hyderabad
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH,Sunrisers Hyderabad
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH,Sunrisers Hyderabad
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH,Sunrisers Hyderabad

In [21]:
# dlm.rename(columns={'winner_x':'winner'},inplace=True)
# dlm.drop(columns='winner_y',inplace=True)
dlm.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,total_runs,player_dismissed,dismissal_kind,fielder,id,season,winner,toss_decision,FullName,ShortName
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,4,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,2,NaN,NaN,NaN,1,2017,Sunrisers Hyderabad,field,Sunrisers Hyderabad,SH

In [16]:
mtch[mtchcols].head()

   id  season                       winner toss_decision
0   1    2017          Sunrisers Hyderabad         field
1   2    2017       Rising Pune Supergiant         field
2   3    2017        Kolkata Knight Riders         field
3   4    2017              Kings XI Punjab         field
4   5    2017  Royal Challengers Bangalore           bat

In [15]:
mtchcols=['id','season','winner','toss_decision']

In [6]:
mtch=pd.read_csv("matches.csv")
mtch.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [8]:
mtch.nunique()

id                 756
season              12
city                32
date               546
team1               15
team2               15
toss_winner         15
toss_decision        2
result               3
dl_applied           2
winner              15
win_by_runs         89
win_by_wickets      11
player_of_match    226
venue               41
umpire1             61
umpire2             65
umpire3             25
dtype: int64

In [3]:
nmt=pd.read_csv('NameTranslation.csv')
nmt['winner']=nmt.FullName
nmt.head()

                      FullName ShortName                       winner
0          Sunrisers Hyderabad        SH          Sunrisers Hyderabad
1               Mumbai Indians        MI               Mumbai Indians
2                Gujarat Lions        GL                Gujarat Lions
3       Rising Pune Supergiant       RPS       Rising Pune Supergiant
4  Royal Challengers Bangalore       RCB  Royal Challengers Bangalore

In [4]:
mtch=pd.merge(mtch,nmt,how='left',indicator=True)
print()
mtch.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,...,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,FullName,ShortName,_merge
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,Sunrisers Hyderabad,SH,both
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,...,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,Rising Pune Supergiant,RPS,both
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,...,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,Kolkata Knight Riders,KKR,both
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,...,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,Kings XI Punjab,KP,both
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,...,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,Royal Challengers Bangalore,RCB,both

In [5]:
mtch._merge.value_counts()

both          752
left_only       4
right_only      0
Name: _merge, dtype: int64

In [ ]:
mtch.isna().sum()

In [24]:
mtch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   season           756 non-null    int64
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(5), object(13)
memory usage: 106.4+ KB

In [27]:
dlv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
 21  id                179078 non-null  object
dtypes: int64(13), object(9)
memory usage: 30.1+ MB

In [26]:
dlv['id']=dlv.match_id.astype(str)

In [28]:
dlm=pd.merge(dlv,mtch[mtchcols],how='left')

ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat

In [36]:
tmp=mtch[mtchcols]
tmp

        id  season                       winner toss_decision
0        1    2017          Sunrisers Hyderabad         field
1        2    2017       Rising Pune Supergiant         field
2        3    2017        Kolkata Knight Riders         field
3        4    2017              Kings XI Punjab         field
4        5    2017  Royal Challengers Bangalore           bat
..     ...     ...                          ...           ...
751  11347    2019               Mumbai Indians         field
752  11412    2019               Mumbai Indians           bat
753  11413    2019               Delhi Capitals         field
754  11414    2019          Chennai Super Kings         field
755  11415    2019               Mumbai Indians           bat

[756 rows x 4 columns]

In [38]:
tmp['id']=tmp.id.astype(str).str.zfill(5)
tmp

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

        id  season                       winner toss_decision
0    00001    2017          Sunrisers Hyderabad         field
1    00002    2017       Rising Pune Supergiant         field
2    00003    2017        Kolkata Knight Riders         field
3    00004    2017              Kings XI Punjab         field
4    00005    2017  Royal Challengers Bangalore           bat
..     ...     ...                          ...           ...
751  11347    2019               Mumbai Indians         field
752  11412    2019               Mumbai Indians           bat
753  11413    2019               Delhi Capitals         field
754  11414    2019          Chennai Super Kings         field
755  11415    2019               Mumbai Indians           bat

[756 rows x 4 columns]

In [37]:
tmp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             756 non-null    int64
 1   season         756 non-null    int64
 2   winner         752 non-null    object
 3   toss_decision  756 non-null    object
dtypes: int64(2), object(2)
memory usage: 23.8+ KB

In [ ]:
pd.concat

In [54]:
tmp1=tmp.loc[tmp.season==2017].reset_index()
tmp1['chkcol']='testing'
tmp2=tmp.loc[tmp.season==2019].reset_index()
tmp2['winner_x']='win'

In [55]:
tmp1

    index     id  season                       winner toss_decision   chkcol
0       0  00001    2017          Sunrisers Hyderabad         field  testing
1       1  00002    2017       Rising Pune Supergiant         field  testing
2       2  00003    2017        Kolkata Knight Riders         field  testing
3       3  00004    2017              Kings XI Punjab         field  testing
4       4  00005    2017  Royal Challengers Bangalore           bat  testing
5       5  00006    2017          Sunrisers Hyderabad         field  testing
6       6  00007    2017               Mumbai Indians         field  testing
7       7  00008    2017              Kings XI Punjab           bat  testing
8       8  00009    2017             Delhi Daredevils         field  testing
9       9  00010    2017               Mumbai Indians         field  testing
10     10  00011    2017        Kolkata Knight Riders         field  testing
11     11  00012    2017               Mumbai Indians         field  testing
12     12  00013    2017                Gujarat Lions         field  testing
13     13  00014    2017        Kolkata Knight Riders         field  testing
14     14  00015    2017             Delhi Daredevils           bat  testing
15     15  00016    2017               Mumbai Indians         field  testing
16     16  00017    2017       Rising Pune Supergiant         field  testing
17     17  00018    2017        Kolkata Knight Riders           bat  testing
18     18  00019    2017          Sunrisers Hyderabad         field  testing
19     19  00020    2017  Royal Challengers Bangalore         field  testing
20     20  00021    2017          Sunrisers Hyderabad           bat  testing
21     21  00022    2017               Mumbai Indians         field  testing
22     22  00023    2017                Gujarat Lions         field  testing
23     23  00024    2017               Mumbai Indians         field  testing
24     24  00025    2017       Rising Pune Supergiant         field  testing
25     25  00026    2017              Kings XI Punjab         field  testing
26     26  00027    2017        Kolkata Knight Riders         field  testing
27     27  00028    2017       Rising Pune Supergiant         field  testing
28     28  00029    2017        Kolkata Knight Riders         field  testing
29     29  00030    2017                Gujarat Lions         field  testing
30     30  00031    2017        Kolkata Knight Riders         field  testing
31     31  00032    2017          Sunrisers Hyderabad         field  testing
32     32  00033    2017       Rising Pune Supergiant         field  testing
33     33  00034    2017               Mumbai Indians           bat  testing
34     34  00035    2017              Kings XI Punjab         field  testing
35     35  00036    2017          Sunrisers Hyderabad         field  testing
36     36  00037    2017               Mumbai Indians           bat  testing
37     37  00038    2017       Rising Pune Supergiant         field  testing
38     38  00039    2017             Delhi Daredevils         field  testing
39     39  00040    2017       Rising Pune Supergiant         field  testing
40     40  00041    2017             Delhi Daredevils         field  testing
41     41  00042    2017              Kings XI Punjab         field  testing
42     42  00043    2017       Rising Pune Supergiant         field  testing
43     43  00044    2017               Mumbai Indians         field  testing
44     44  00045    2017        Kolkata Knight Riders         field  testing
45     45  00046    2017                Gujarat Lions         field  testing
46     46  00047    2017          Sunrisers Hyderabad           bat  testing
47     47  00048    2017              Kings XI Punjab         field  testing
48     48  00049    2017             Delhi Daredevils         field  testing
49     49  00050    2017              Kings XI Punjab         field  testing
50     50  00051    2017             Delhi Daredevils           bat  testing
51     51  00052    2017          Sunrisers Hyderabad         field  testing
52     52  00053    2017               Mumbai Indians         field  testing
53     53  00054    2017       Rising Pune Supergiant         field  testing
54     54  00055    2017  Royal Challengers Bangalore           bat  testing
55     55  00056    2017       Rising Pune Supergiant         field  testing
56     56  00057    2017        Kolkata Knight Riders         field  testing
57     57  00058    2017               Mumbai Indians         field  testing
58     58  00059    2017               Mumbai Indians           bat  testing

In [56]:
tmp2

    index     id  season                       winner toss_decision winner_x
0     696  11137    2019          Chennai Super Kings         field      win
1     697  11138    2019        Kolkata Knight Riders         field      win
2     698  11139    2019               Delhi Capitals         field      win
3     699  11140    2019              Kings XI Punjab         field      win
4     700  11141    2019          Chennai Super Kings           bat      win
5     701  11142    2019        Kolkata Knight Riders         field      win
6     702  11143    2019               Mumbai Indians         field      win
7     703  11144    2019          Sunrisers Hyderabad           bat      win
8     704  11145    2019              Kings XI Punjab         field      win
9     705  11146    2019               Delhi Capitals         field      win
10    706  11147    2019          Sunrisers Hyderabad         field      win
11    707  11148    2019          Chennai Super Kings         field      win
12    708  11149    2019              Kings XI Punjab         field      win
13    709  11150    2019             Rajasthan Royals         field      win
14    710  11151    2019               Mumbai Indians         field      win
15    711  11152    2019          Sunrisers Hyderabad         field      win
16    712  11153    2019        Kolkata Knight Riders         field      win
17    713  11309    2019          Chennai Super Kings           bat      win
18    714  11310    2019               Mumbai Indians         field      win
19    715  11311    2019               Delhi Capitals         field      win
20    716  11312    2019        Kolkata Knight Riders         field      win
21    717  11313    2019              Kings XI Punjab         field      win
22    718  11314    2019          Chennai Super Kings         field      win
23    719  11315    2019               Mumbai Indians         field      win
24    720  11316    2019          Chennai Super Kings         field      win
25    721  11317    2019               Delhi Capitals         field      win
26    722  11318    2019             Rajasthan Royals         field      win
27    723  11319    2019  Royal Challengers Bangalore         field      win
28    724  11320    2019          Chennai Super Kings         field      win
29    725  11321    2019               Delhi Capitals         field      win
30    726  11322    2019               Mumbai Indians         field      win
31    727  11323    2019              Kings XI Punjab         field      win
32    728  11324    2019          Sunrisers Hyderabad           bat      win
33    729  11325    2019               Mumbai Indians           bat      win
34    730  11326    2019  Royal Challengers Bangalore         field      win
35    731  11327    2019             Rajasthan Royals         field      win
36    732  11328    2019               Delhi Capitals         field      win
37    733  11329    2019          Sunrisers Hyderabad         field      win
38    734  11330    2019  Royal Challengers Bangalore         field      win
39    735  11331    2019               Delhi Capitals         field      win
40    736  11332    2019          Chennai Super Kings         field      win
41    737  11333    2019  Royal Challengers Bangalore         field      win
42    738  11334    2019             Rajasthan Royals         field      win
43    739  11335    2019               Mumbai Indians         field      win
44    740  11336    2019             Rajasthan Royals         field      win
45    741  11337    2019               Delhi Capitals           bat      win
46    742  11338    2019        Kolkata Knight Riders         field      win
47    743  11339    2019          Sunrisers Hyderabad         field      win
48    744  11340    2019                          NaN         field      win
49    745  11341    2019          Chennai Super Kings         field      win
50    746  11342    2019               Mumbai Indians           bat      win
51    747  11343    2019        Kolkata Knight Riders         field      win
52    748  11344    2019               Delhi Capitals           bat      win
53    749  11345    2019  Royal Challengers Bangalore         field      win
54    750  11346    2019              Kings XI Punjab         field      win
55    751  11347    2019               Mumbai Indians         field      win
56    752  11412    2019               Mumbai Indians           bat      win
57    753  11413    2019               Delhi Capitals         field      win
58    754  11414    2019          Chennai Super Kings         field      win
59    755  11415    2019               Mumbai Indians           bat      win

In [52]:
pd.concat([tmp1,tmp2],axis=0)

,id,season,winner,toss_decision,chkcol,winner_x
0,00001,2017,Sunrisers Hyderabad,field,testing,NaN
1,00002,2017,Rising Pune Supergiant,field,testing,NaN
2,00003,2017,Kolkata Knight Riders,field,testing,NaN
3,00004,2017,Kings XI Punjab,field,testing,NaN
4,00005,2017,Royal Challengers Bangalore,bat,testing,NaN
...,...,...,...,...,...,...
751,11347,2019,Mumbai Indians,field,NaN,win
752,11412,2019,Mumbai Indians,bat,NaN,win
753,11413,2019,Delhi Capitals,field,NaN,win
754,11414,2019,Chennai Super Kings,field,NaN,win
755,11415,2019,Mumbai Indians,bat,NaN,win

In [58]:
pd.concat([tmp1,tmp2],axis=1)

,index,id,season,winner,toss_decision,chkcol,index,id,season,winner,toss_decision,winner_x
0,0.0,00001,2017.0,Sunrisers Hyderabad,field,testing,696,11137,2019,Chennai Super Kings,field,win
1,1.0,00002,2017.0,Rising Pune Supergiant,field,testing,697,11138,2019,Kolkata Knight Riders,field,win
2,2.0,00003,2017.0,Kolkata Knight Riders,field,testing,698,11139,2019,Delhi Capitals,field,win
3,3.0,00004,2017.0,Kings XI Punjab,field,testing,699,11140,2019,Kings XI Punjab,field,win
4,4.0,00005,2017.0,Royal Challengers Bangalore,bat,testing,700,11141,2019,Chennai Super Kings,bat,win
5,5.0,00006,2017.0,Sunrisers Hyderabad,field,testing,701,11142,2019,Kolkata Knight Riders,field,win
6,6.0,00007,2017.0,Mumbai Indians,field,testing,702,11143,2019,Mumbai Indians,field,win
7,7.0,00008,2017.0,Kings XI Punjab,bat,testing,703,11144,2019,Sunrisers Hyderabad,bat,win
8,8.0,00009,2017.0,Delhi Daredevils,field,testing,704,11145,2019,Kings XI Punjab,field,win
9,9.0,00010,2017.0,Mumbai Indians,field,testing,705,11146,2019,Delhi Capitals,field,win
10,10.0,00011,2017.0,Kolkata Knight Riders,field,testing,706,11147,2019,Sunrisers Hyderabad,field,win
11,11.0,00012,2017.0,Mumbai Indians,field,testing,707,11148,2019,Chennai Super Kings,field,win
12,12.0,00013,2017.0,Gujarat Lions,field,testing,708,11149,2019,Kings XI Punjab,field,win
13,13.0,00014,2017.0,Kolkata Knight Riders,field,testing,709,11150,2019,Rajasthan Royals,field,win
14,14.0,00015,2017.0,Delhi Daredevils,bat,testing,710,11151,2019,Mumbai Indians,field,win
15,15.0,00016,2017.0,Mumbai Indians,field,testing,711,11152,2019,Sunrisers Hyderabad,field,win
16,16.0,00017,2017.0,Rising Pune Supergiant,field,testing,712,11153,2019,Kolkata Knight Riders,field,win
17,17.0,00018,2017.0,Kolkata Knight Riders,bat,testing,713,11309,2019,Chennai Super Kings,bat,win
18,18.0,00019,2017.0,Sunrisers Hyderabad,field,testing,714,11310,2019,Mumbai Indians,field,win
19,19.0,00020,2017.0,Royal Challengers Bangalore,field,testing,715,11311,2019,Delhi Capitals,field,win
20,20.0,00021,2017.0,Sunrisers Hyderabad,bat,testing,716,11312,2019,Kolkata Knight Riders,field,win
21,21.0,00022,2017.0,Mumbai Indians,field,testing,717,11313,2019,Kings XI Punjab,field,win
22,22.0,00023,2017.0,Gujarat Lions,field,testing,718,11314,2019,Chennai Super Kings,field,win
23,23.0,00024,2017.0,Mumbai Indians,field,testing,719,11315,2019,Mumbai Indians,field,win
24,24.0,00025,2017.0,Rising Pune Supergiant,field,testing,720,11316,2019,Chennai Super Kings,field,win
25,25.0,00026,2017.0,Kings XI Punjab,field,testing,721,11317,2019,Delhi Capitals,field,win
26,26.0,00027,2017.0,Kolkata Knight Riders,field,testing,722,11318,2019,Rajasthan Royals,field,win
27,27.0,00028,2017.0,Rising Pune Supergiant,field,testing,723,11319,2019,Royal Challengers Bangalore,field,win
28,28.0,00029,2017.0,Kolkata Knight Riders,field,testing,724,11320,2019,Chennai Super Kings,field,win
29,29.0,00030,2017.0,Gujarat Lions,field,testing,725,11321,2019,Delhi Capitals,field,win
30,30.0,00031,2017.0,Kolkata Knight Riders,field,testing,726,11322,2019,Mumbai Indians,field,win
31,31.0,00032,2017.0,Sunrisers Hyderabad,field,testing,727,11323,2019,Kings XI Punjab,field,win
32,32.0,00033,2017.0,Rising Pune Supergiant,field,testing,728,11324,2019,Sunrisers Hyderabad,bat,win
33,33.0,00034,2017.0,Mumbai Indians,bat,testing,729,11325,2019,Mumbai Indians,bat,win
34,34.0,00035,2017.0,Kings XI Punjab,field,testing,730,11326,2019,Royal Challengers Bangalore,field,win
35,35.0,00036,2017.0,Sunrisers Hyderabad,field,testing,731,11327,2019,Rajasthan Royals,field,win
36,36.0,00037,2017.0,Mumbai Indians,bat,testing,732,11328,2019,Delhi Capitals,field,win
37,37.0,00038,2017.0,Rising Pune Supergiant,field,testing,733,11329,2019,Sunrisers Hyderabad,field,win
38,38.0,00039,2017.0,Delhi Daredevils,field,testing,734,11330,2019,Royal Challengers Bangalore,field,win
39,39.0,00040,2017.0,Rising Pune Supergiant,field,testing,735,11331,2019,Delhi Capitals,field,win
40,40.0,00041,2017.0,Delhi Daredevils,field,testing,736,11332,2019,Chennai Super Kings,field,win
41,41.0,00042,2017.0,Kings XI Punjab,field,testing,737,11333,2019,Royal Challengers Bangalore,field,win
42,42.0,00043,2017.0,Rising Pune Supergiant,field,testing,738,11334,2019,Rajasthan Royals,field,win
43,43.0,00044,2017.0,Mumbai Indians,field,testing,739,11335,2019,Mumbai Indians,field,win
44,44.0,00045,2017.0,Kolkata Knight Riders,field,testing,740,11336,2019,Rajasthan Royals,field,win
45,45.0,00046,2017.0,Gujarat Lions,field,testing,741,11337,2019,Delhi Capitals,bat,win
46,46.0,00047,2017.0,Sunrisers Hyderabad,bat,testing,742,11338,2019,Kolkata Knight Riders,field,win
47,47.0,00048,2017.0,Kings XI Punjab,field,testing,743,11339,2019,Sunrisers Hyderabad,field,win
48,48.0,00049,2017.0,Delhi Daredevils,field,testing,744,11340,2019,NaN,field,win
49,49.0,00050,2017.0,Kings XI Punjab,field,testing,745,11341,2019,Chennai Super Kings,field,win
50,50.0,00051,2017.0,Delhi Daredevils,bat,testing,746,11342,2019,Mumbai Indians,bat,win
51,51.0,00052,2017.0,Sunrisers Hyderabad,field,testing,747,11343,2019,Kolkata Knight Riders,field,win
52,52.0,00053,2017.0,Mumbai Indians,field,testing,748,11344,2019,Delhi Capitals,bat,win
53,53.0,00054,2017.0,Rising Pune Supergiant,field,testing,749,11345,2019,Royal Challengers Bangalore,field,win
54,54.0,00055,2017.0,Royal Challengers Bangalore,bat,testing,750,11346,2019,Kings XI Punjab,field,win
55,55.0,00056,2017.0,Rising Pune Supergiant,field,testing,751,11347,2019,Mumbai Indians,field,win
56,56.0,00057,2017.0,Kolkata Knight Riders,field,testing,752,11412,2019,Mumbai Indians,bat,win
57,57.0,00058,2017.0,Mumbai Indians,field,testing,753,11413,2019,Delhi Capitals,field,win
58,58.0,00059,2017.0,Mumbai Indians,bat,testing,754,11414,2019,Chennai Super Kings,field,win
59,NaN,NaN,NaN,NaN,NaN,NaN,755,11415,2019,Mumbai Indians,bat,win

In [59]:
tmp1=tmp.loc[tmp.season==2017].reset_index()
tmp1.head()

   index     id  season                       winner toss_decision
0      0  00001    2017          Sunrisers Hyderabad         field
1      1  00002    2017       Rising Pune Supergiant         field
2      2  00003    2017        Kolkata Knight Riders         field
3      3  00004    2017              Kings XI Punjab         field
4      4  00005    2017  Royal Challengers Bangalore           bat

In [61]:
tmp1.set_index('winner',inplace=True)
tmp1.head()

                             index     id  season toss_decision
winner
Sunrisers Hyderabad              0  00001    2017         field
Rising Pune Supergiant           1  00002    2017         field
Kolkata Knight Riders            2  00003    2017         field
Kings XI Punjab                  3  00004    2017         field
Royal Challengers Bangalore      4  00005    2017           bat

In [63]:
nmt.set_index('winner',inplace=True)
nmt.head()

                                                FullName ShortName
winner
Sunrisers Hyderabad                  Sunrisers Hyderabad        SH
Mumbai Indians                            Mumbai Indians        MI
Gujarat Lions                              Gujarat Lions        GL
Rising Pune Supergiant            Rising Pune Supergiant       RPS
Royal Challengers Bangalore  Royal Challengers Bangalore       RCB

In [69]:
dtlst=[tmp1,tmp2,nmt]

pd.concat(dtlst,axis=0)

,index,id,season,toss_decision,winner,winner_x,FullName,ShortName
Sunrisers Hyderabad,0.0,00001,2017.0,field,NaN,NaN,NaN,NaN
Rising Pune Supergiant,1.0,00002,2017.0,field,NaN,NaN,NaN,NaN
Kolkata Knight Riders,2.0,00003,2017.0,field,NaN,NaN,NaN,NaN
Kings XI Punjab,3.0,00004,2017.0,field,NaN,NaN,NaN,NaN
Royal Challengers Bangalore,4.0,00005,2017.0,bat,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
Deccan Chargers,NaN,NaN,NaN,NaN,NaN,NaN,Deccan Chargers,DC
Kochi Tuskers Kerala,NaN,NaN,NaN,NaN,NaN,NaN,Kochi Tuskers Kerala,KTK
Pune Warriors,NaN,NaN,NaN,NaN,NaN,NaN,Pune Warriors,PW
Rising Pune Supergiants,NaN,NaN,NaN,NaN,NaN,NaN,Rising Pune Supergiants,RPS
Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,Delhi Capitals,DLC

In [65]:
nmt.shape

(15, 2)

In [66]:
tmp1.shape

(59, 4)